version: "3"  

# Persistent storage 
volumes:
  prometheus_data: {}
  grafana_data: {}
  loki_data: {}

# Bridge network
networks:
  monitoring:
    driver: bridge

services:
  ## Prometheus Service
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    networks:
      - monitoring
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"  # Explicitly specify config file
      - "--storage.tsdb.path=/prometheus"                # Path to store data
      - "--web.enable-lifecycle"                         # Enable HTTP-based reload triggers
    healthcheck:  # Add a health check to ensure the service is running
      test: ["CMD-SHELL", "wget -q --spider http://localhost:9090/-/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  ## Grafana Service
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - grafana_data:/var/lib/grafana
    env_file: # creds file
      - ./grafana/grafana.config
    depends_on:
      - prometheus
    healthcheck:  # Health check to ensure Grafana is ready
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000/login || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

## Loki Service
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml    
    networks:
      - monitoring

## Loki Service
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log:ro
      - ./promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - monitoring