---
name: Hello World

on:
    push:
        branches:
        - main
    workflow_dispatch:

jobs:
    say-hello-inline-bash:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello, World!"

    show-time:
        runs-on: ubuntu-latest
        steps:
            - name: tell time
              run: echo "The time is $(date)"

    show-version:
        runs-on: ubuntu-latest
        needs: show-time   
        steps:
            - name: show version
              run: echo "The linux version is $(lsb_release -a)"           